### ISSUE TITLE
USB vendor string does not match the vendor ID

### ISSUE THREAD

**Issue by kierdavis** [srobo/power-v4-fw#1]
The USB vendor ID (defined [here](https://github.com/sourcebots/power-v4-fw/blob/master/Makefile#L18)) is 0x1BDA which is allocated to the University of Southampton. However the corresponding string (defined [here](https://github.com/sourcebots/power-v4-fw/blob/master/pbusb.c#L81)) actually says "Student Robotics". It is recommended that the vendor string should match the vendor ID.

EDIT: this is also an upstream issue.

Resolving this would also require a corresponding change to robotd's code for identifying new boards, unless sourcebots/robotd#41 (which removes the reliance on using the strings as identification keys) is merged.

**Comment by trickeydan** [comment]
@RealOrangeOne Please close this as `invalid`. @TylerWard says that this is actually valid in the USB spec.
