### ISSUE TITLE
Power board resets if too many buzzes are enqueued

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/power-v4-fw#3]
According to https://github.com/srobo/docs/pull/99 and https://github.com/srobo/docs/issues/97 there's a bug in the power board firmware such that if too many buzzer requests are enqueued then the sample ring buffer in [piezo.c](https://github.com/srobo/power-v4-fw/blob/master/piezo.c#L22) for them will overflow, leading to the power board resetting and USB errors.

**Comment by WillB97** [comment]
#13 fixes this, there is no longer a ringbuffer on the MCU.
