### ISSUE TITLE
Handle negative battery currents

### ISSUE THREAD

**Issue by richardbarlow** [srobo/power-v4-fw#4]
At the moment the battery current is cast to an unsigned int even though it's a signed value. This results in the over current protection tripping when the battery current goes negative (when the unsigned int effectively wraps). This can occur when a robot has a large mass and get get up to a high speed. If the robot is moving at a high speed and then commanded to instantaneously drop to a lower speed (or change direction) the kinetic energy results in the battery being momentarily charged (battery current negative). This is completely harmless and expected behaviour. In general the energy has originally come from the battery, so there is no risk of overcharging. There is a very slight risk of overcharging if an external power source is present (e.g. the robot being pushed by an external force such as gravity or a hand), but this risk is exceptionally low due to the rest of the kit constantly discharging the battery.

The battery current should be treated as a signed value and all code paths that use that value (including the low pass filter) tested to ensure that the behaviour is as desired. The current limit set on the output of the low pass filter should be bi-polar and probably asymmetric (i.e. it should have a negative limit of say 4A.)

**Comment by WillB97** [comment]
Fixed in #13. Negative transients now have their own limits.
