### ISSUE TITLE
Firmware support for flashing the run LED

### ISSUE THREAD

**Issue by kierdavis** [srobo/power-v4-fw#6]
Traditionally the run LED flashes while the robot software is waiting for the user to press the start button. Right now this is done from the Python code, but this could be easily moved to the firmware. It could be implemented by having three states for the run LED ("off", "on" and "flashing"), and configuring a new hardware timer or piggybacking off a timer that's already in use.

This would make j5api/j5#274 a non-issue.

(originally posted at https://github.com/j5api/sr-power-v4-fw/issues/10)

**Comment by WillB97** [comment]
Fixed in #13
